Added new paginator, new grid buttons and new fonts
matllubos/django-is-core pull request #407
Opened 2020-11-09 11:05 UTC by matllubos

2020-11-09 12:05 UTC, rubickcz commented on is_core/contrib/background_export/templates/is_core/generic_views/table.html
> +            <button class="btn btn-secondary dropdown-toggle" data-toggle="dropdown"><i class="fa fa-file-export"></i> <span class="caret"></span></button>
Can you pls add tooltip for the icon-only buttons? Adding these attributes should be enough:
```
data-toggle="tooltip" title="Tooltip on bottom"
```

2020-11-09 12:06 UTC, rubickcz commented on is_core/templates/is_core/generic_views/base_table.html
> +            </ul>
These buttons also deserve tooltip.

2020-11-09 12:06 UTC, rubickcz requested changes
Add tooltips pls.

2020-11-10 07:36 UTC, Formulka reviewed
just a typo

2020-11-10 07:36 UTC, Formulka commented on is_core/locale/cs/LC_MESSAGES/django.po
> +msgstr "Zobrazit/skýrt sloupce"
skýrt -> skrýt

2020-11-10 09:36 UTC, rubickcz approved these changes

2020-11-10 11:29 UTC, merged